#!/bin/bash
set -e

sudo apt update -qq
sudo apt install -y -qq curl jq unzip dos2unix wget

cd ..
mkdir -p server
cd server

MC_VERSION="${MC_VERSION:-latest}"
echo "> Using Minecraft version: $MC_VERSION"

SERVER_JARFILE=server.jar
FABRIC_VERSION=latest

if [ "$MC_VERSION" = "latest" ]; then
  MC_VERSION=$(curl -s https://meta.fabricmc.net/v2/versions/game \
    | jq -r '.[] | select(.stable==true) | .version' | head -n1)
elif [ "$MC_VERSION" = "snapshot" ]; then
  MC_VERSION=$(curl -s https://meta.fabricmc.net/v2/versions/game \
    | jq -r '.[] | select(.stable==false) | .version' | head -n1)
fi

[ "$FABRIC_VERSION" = "latest" ] && \
  FABRIC_VERSION=$(curl -s https://meta.fabricmc.net/v2/versions/installer | jq -r '.[0].version')

wget -q -O fabric-installer.jar \
  https://maven.fabricmc.net/net/fabricmc/fabric-installer/$FABRIC_VERSION/fabric-installer-$FABRIC_VERSION.jar

java -jar fabric-installer.jar server \
  -mcversion "$MC_VERSION" \
  -downloadMinecraft

echo "> Fabric install complete"
