#!/bin/bash
# Paper Installation Script

set -e

sudo apt update -qq
sudo apt install -y -qq curl jq > /dev/null

cd ..
mkdir -p server
cd server

# -----------------------------
# Minecraft version (from installJava)
# -----------------------------
MINECRAFT_VERSION="${MC_VERSION:-latest}"
echo "> Using Minecraft version: $MINECRAFT_VERSION"

# -- CONFIG --
BUILD_NUMBER=latest
PROJECT=paper
SERVER_JARFILE=server.jar
# ------------

if [ -n "${DL_PATH}" ]; then
    DOWNLOAD_URL=$(eval echo "${DL_PATH}")
else
    LATEST_VERSION=$(curl -s "https://api.papermc.io/v2/projects/${PROJECT}" | jq -r '.versions[-1]')

    if [ "$MINECRAFT_VERSION" = "latest" ]; then
        MINECRAFT_VERSION="$LATEST_VERSION"
        echo "> Resolved latest version: $MINECRAFT_VERSION"
    fi

    LATEST_BUILD=$(curl -s \
      "https://api.papermc.io/v2/projects/${PROJECT}/versions/${MINECRAFT_VERSION}/builds" \
      | jq -r '.builds | map(select(.channel=="default")|.build) | .[-1]')

    [ "$BUILD_NUMBER" = "latest" ] && BUILD_NUMBER="$LATEST_BUILD"

    JAR_NAME="${PROJECT}-${MINECRAFT_VERSION}-${BUILD_NUMBER}.jar"
    DOWNLOAD_URL="https://api.papermc.io/v2/projects/${PROJECT}/versions/${MINECRAFT_VERSION}/builds/${BUILD_NUMBER}/downloads/${JAR_NAME}"
fi

echo "> Downloading server.jar"
[ -f server.jar ] && mv server.jar server.jar.old
curl -sSL -o server.jar "$DOWNLOAD_URL"

if [ ! -f server.properties ]; then
    curl -sSL -o server.properties \
      https://raw.githubusercontent.com/parkervcp/eggs/master/minecraft/java/server.properties
fi

echo "> Paper install complete"
