#!/bin/bash
set -e

sudo apt update -qq
sudo apt install -y -qq jq curl

cd ..
mkdir -p server
cd server

LATEST_RELEASE=$(curl -s https://launchermeta.mojang.com/mc/game/version_manifest.json | jq -r '.latest.release')
LATEST_SNAPSHOT=$(curl -s https://launchermeta.mojang.com/mc/game/version_manifest.json | jq -r '.latest.snapshot')

VANILLA_VERSION="${MC_VERSION:-latest}"
echo "> Using Minecraft version: $VANILLA_VERSION"

if [ "$VANILLA_VERSION" = "latest" ]; then
  TARGET="$LATEST_RELEASE"
elif [ "$VANILLA_VERSION" = "snapshot" ]; then
  TARGET="$LATEST_SNAPSHOT"
else
  TARGET="$VANILLA_VERSION"
fi

MANIFEST_URL=$(curl -s https://launchermeta.mojang.com/mc/game/version_manifest.json \
  | jq -r --arg V "$TARGET" '.versions[] | select(.id==$V) | .url')

if [ -z "$MANIFEST_URL" ]; then
  echo "Invalid Minecraft version"
  exit 1
fi

DOWNLOAD_URL=$(curl -s "$MANIFEST_URL" | jq -r '.downloads.server.url')

curl -sSL -o server.jar "$DOWNLOAD_URL"
echo "> Vanilla install complete"
