#!/bin/bash

set -e

mkdir -p bin
chmod +x *

export MAIN_DIR="$PWD"

echo "Which Server do you want to install?"
echo "Type [1] Java Server"
echo "Type [2] Bedrock Server"
read -rp "> " choiceForServer

# -----------------------------
# Server choice
# -----------------------------
if [[ -z "$choiceForServer" ]]; then
  echo "> Invalid response"
  ./install

elif [[ "$choiceForServer" == "1" ]]; then
  echo "> Running Java installation..."
  ./installJava

elif [[ "$choiceForServer" == "2" ]]; then
  echo "> Running Bedrock installation..."
  ./installBedrock

else
  echo "> Invalid response"
  ./install
fi

# -----------------------------
# AFK 
# -----------------------------
echo "> Installing AFK monitor..."
python3 -m pip install --user bpytop

echo "> Install finished."
