#!/bin/bash
mkdir bin
chmod +x *
export MAIN_DIR=$PWD
echo "Which Server do you want to install?"
echo "Type [1] Java Server"
echo "Type [2] Bedrock Server"

choiceForServer=1
read choiceForServer

# Installing Latest Java JDK and playit

JDK_URL="https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.deb"

wget -q "$JDK_URL" -O bin/java.deb
cd $MAIN_DIR/bin
echo "> Installing Java JDK 21..."
sudo dpkg -i java.deb

cd $MAIN_DIR
# If choice is 0 or null then run this command
if [[ -z $choiceForServer ]]; then
  echo "> Invalid Response. Please try again."
  ./install

# If choice is 1 then run this command
elif [[ $choiceForServer == 1 ]]; then
  echo "> Running Java Installation..."
  ./installJava

# If choice is 2 then run this command
elif [[ $choiceForServer == 2 ]]; then
  echo "> Running Bedrock Installation..."
  ./installBedrock
else
  echo "> Invalid Response. Please try again."
  ./install
fi
echo "> Installing AFK (Away From Keyboard) Script "
python3 -m pip install bpytop
echo ""
